this commit adds code for ticket 6 viewing comments for an article
hja7333/nc-news pull request #3
Opened 2023-03-16 16:32 UTC by hja7333

Dave gave permission for this pr after 4pm today. Thanks Dave

2023-03-16 16:50 UTC, dav3rid requested changes
It does look a little janky in mobile view - you could allow the image for an article to spread out slightly more.

There are 2 errors I found regarding your css modules
- Don't use absolute paths as they rely on being run from your machine directly - use relative paths instead eg `import styles from "/Users/alhunt/northcoders/frontend/nc-news/src/styles/ArticleContainer.module.css";` should be `import styles from "../styles/ArticleContainer.module.css";`

2023-03-16 16:50 UTC, dav3rid commented on src/components/Comments.jsx
> +      console.log(data.comments);
Can strip out this console log here

2023-03-16 16:50 UTC, dav3rid commented on src/components/Comments.jsx
> +
You'll want to implement the `isLoading` pattern here - there is currently no indication to the user that comments are indeed loading

2023-03-16 16:50 UTC, dav3rid commented on src/pages/SingleArticle.jsx
> +          alt={`${article.title}`}
this doesn't need to be in a template literal

2023-03-16 16:50 UTC, dav3rid commented on src/utils/api.js
> +const newsApi = axios.create({
Nice renaming - definitely clearer

2023-03-17 09:47 UTC, JVal-NC commented on src/pages/HomePage.jsx
>  import styles from "/Users/alhunt/northcoders/frontend/nc-news/src/styles/ArticleContainer.module.css";
Can you fix this import to avoid importing from local files. New PR after please!

2023-03-17 09:47 UTC, JVal-NC reviewed
Hi Al, can you fix the import in the comments and do another PR, thanks!

2023-03-17 11:31 UTC, dav3rid approved these changes

2023-03-17 11:33 UTC, merged